/*
 * netfix.h - switches for the Ethernet / lwIP thread-safety fixes (build 10049)
 *
 * Background: detectors stopped sending UDP ("UDPSTALL"). In every case b2's capture
 * showed one packet lost exactly one send-ring lap (96 sends) before the stall, and that
 * packet's pbuf reference never came back. Three causes were found in the network stack
 * as configured here (see UDP_SEND_QUEUE.md and the commit messages):
 *
 *  A  NETFIX_HAL_ETH_TX_ORDER  Drivers/.../stm32f7xx_hal_eth.c, ETH_Prepare_Tx_Descriptors():
 *       ST's driver (Cube FW F7 V1.17.1) hands the FIRST descriptor of a multi-buffer frame
 *       to the DMA before the rest of the chain is built, and clears the next descriptor's
 *       FS bit before checking that it is free. Every frame we send is a 2-3 buffer chain.
 *       Ported from ST's later fix (Cube FW F7 V1.17.4): OWN of the first descriptor is set
 *       last; FS is cleared only after the free check; PRIMASK is saved/restored.
 *       NOTE: Drivers/ is regenerated by CubeMX. If that happens the patch disappears, and
 *       the link fails on netfix_hal_eth_patch (defined only by the patched driver).
 *
 *  B  NETFIX_LWIP_PROTECT      SYS_LIGHTWEIGHT_PROT was 0 (since the initial commit, also in
 *       the .ioc), with LWIP_ALLOW_MEM_FREE_FROM_OTHER_CONTEXT=1, so lwIP's own protection
 *       of pbuf reference counts, memp pools and the heap compiled to nothing while several
 *       tasks use lwIP. Now on, using FreeRTOS BASEPRI critical sections (a few cycles
 *       each) instead of ST's mutex-based sys_arch_protect().
 *
 *  C  NETFIX_TX_MUTEX          LWIP/Target/ethernetif.c low_level_output(): the driver used
 *       one global ETH_TxPacketConfig and unprotected HAL ring state, and could block in
 *       its busy-retry with that global live. Several tasks reach it (netsendtask, tcpip
 *       thread, the low-priority task via raw API calls, the link thread). Now a private
 *       mutex (deliberately NOT lwIP's core lock, which would deadlock) serialises the
 *       transmit path, TxConfig is per call, the busy wait no longer holds the mutex and
 *       is bounded, and the sticky HAL BUSY error bit is cleared each attempt.
 *
 *  D  NETFIX_DIAG              Console-only diagnostics: a small flight recorder of TX
 *       calls/frees (task, pbuf, length), TX mutex contention counters, a richer lwIP
 *       assertion handler, a boot line, and a TXDIAG block added to the UDPSTALL report.
 *
 * Set a switch to 0 to get the previous behaviour of that part (for bisecting).
 * Nothing here touches the ADC ISR or the ADC/producer task.
 */
#ifndef NETFIX_H_
#define NETFIX_H_

#include <stdint.h>

#define NETFIX_HAL_ETH_TX_ORDER		1
#define NETFIX_LWIP_PROTECT			1
#define NETFIX_TX_MUTEX				1
#define NETFIX_DIAG					1

#ifdef __cplusplus
extern "C" {
#endif

/* Markers, referenced from netfix_banner(): defined only by the patched ST driver
 * (stm32f7xx_hal_eth.c) and by the patched low_level_output() (ethernetif.c). If CubeMX
 * regenerates those files and restores the stock code, the link fails. */
extern const uint32_t netfix_hal_eth_patch;
extern const uint32_t netfix_ethernetif_patch;

/* ethernetif.c */
void netfix_banner(void);							/* boot line: which fixes are built in */
void nettx_diag_print(const char *tag, int trace_lines);	/* TX-path state + last events, console only */
void nettx_diag_periodic(void);						/* prints one NETDIAG: line only when a counter moved */
void net_lwip_assert(const char *msg, int line, const char *file);	/* LWIP_PLATFORM_ASSERT */

#ifdef __cplusplus
}
#endif

#endif /* NETFIX_H_ */
