/*
 * netfix.h - switches for the Ethernet / lwIP thread-safety fixes (build 10049)
 *
 * Background: detectors stopped sending UDP ("udpstall"). In every case b2's capture
 * showed one packet lost exactly one send-ring lap (96 sends) before the stall, and that
 * packet's pbuf reference never came back. Three causes were found in the network stack
 * as configured here (see UDP_SEND_QUEUE.md and the commit messages):
 *
 *  A  NETFIX_HAL_ETH_TX_ORDER  Drivers/.../stm32f7xx_hal_eth.c, ETH_Prepare_Tx_Descriptors():
 *       ST's driver (Cube FW F7 V1.17.1) hands the FIRST descriptor of a multi-buffer frame
 *       to the DMA before the rest of the chain is built, and clears the next descriptor's
 *       FS bit before checking that it is free. Every frame we send is a 2-3 buffer chain.
 *       Ported from ST's later fix (Cube FW F7 V1.17.4): OWN of the first descriptor is set
 *       last; FS is cleared only after the free check; PRIMASK is saved/restored.
 *       NOTE: Drivers/ is regenerated by CubeMX. If that happens the patch disappears, and
 *       the link fails on netfix_hal_eth_patch (defined only by the patched driver).
 *
 *  B  NETFIX_LWIP_PROTECT      SYS_LIGHTWEIGHT_PROT was 0 (since the initial commit, also in
 *       the .ioc), with LWIP_ALLOW_MEM_FREE_FROM_OTHER_CONTEXT=1, so lwIP's own protection
 *       of pbuf reference counts, memp pools and the heap compiled to nothing while several
 *       tasks use lwIP. Now on, using FreeRTOS BASEPRI critical sections (a few cycles
 *       each) instead of ST's mutex-based sys_arch_protect().
 *
 *  C  NETFIX_TX_MUTEX          LWIP/Target/ethernetif.c low_level_output(): the driver used
 *       one global ETH_TxPacketConfig and unprotected HAL ring state, and could block in
 *       its busy-retry with that global live. Several tasks reach it (netsendtask, tcpip
 *       thread, the low-priority task via raw API calls, the link thread). Now a private
 *       mutex (deliberately NOT lwIP's core lock, which would deadlock) serialises the
 *       transmit path, TxConfig is per call, the busy wait no longer holds the mutex and
 *       is bounded, and the sticky HAL BUSY error bit is cleared each attempt.
 *
 *  E  NETFIX_CORE_LOCK        (build 10055) raw lwIP calls made outside tcpip_thread take the
 *       core lock (Core/Inc/netcore.h): netsendtask's udp_sendto(), startudp() setup, DNS
 *       lookups, the HTTP client, httpd_init() and the Ethernet link thread's netif_set_*.
 *       0 = unlocked as before.
 *
 *  F  NETFIX_CORE_CHECK       test builds only: LWIP_ASSERT_CORE_LOCKED() (called by every raw API
 *       entry) prints a netcore: line for a call made without the core lock, once per call site,
 *       and counts them (netcore_violations). Armed after MX_LWIP_Init(), whose netif_add()/
 *       dhcp_start() run unlocked at boot (generated code, before any traffic).
 *
 *  D  NETFIX_DIAG              Console-only diagnostics: a small flight recorder of TX
 *       calls/frees (task, pbuf, length), TX mutex contention counters, a richer lwIP
 *       assertion handler, a boot check, and a nettx: block added to the udpstall: report.
 *
 * Set a switch to 0 to get the previous behaviour of that part (for bisecting).
 * Nothing here touches the ADC ISR or the ADC/producer task.
 */
#ifndef NETFIX_H_
#define NETFIX_H_

#include <stdint.h>

#define NETFIX_HAL_ETH_TX_ORDER		1
#define NETFIX_LWIP_PROTECT			1
#define NETFIX_TX_MUTEX				1
#define NETFIX_DIAG					1
#define NETFIX_CORE_LOCK			1
#define NETFIX_CORE_CHECK			0

#ifdef __cplusplus
extern "C" {
#endif

/* Markers, referenced from netfix_banner(): defined only by the patched ST driver
 * (stm32f7xx_hal_eth.c) and by the patched low_level_output() (ethernetif.c). If CubeMX
 * regenerates those files and restores the stock code, the link fails. */
extern const uint32_t netfix_hal_eth_patch;
extern const uint32_t netfix_ethernetif_patch;

/* ethernetif.c */
void netfix_banner(void);							/* boot check: prints a netfix: line only if a fix is switched off */
void nettx_diag_print(const char *tag, int trace_lines);	/* TX-path state + last events, console only */
void nettx_diag_periodic(void);						/* disabled: used to print a line when the TX mutex was contended */
void net_lwip_assert(const char *msg, int line, const char *file);	/* LWIP_PLATFORM_ASSERT */
void netcore_check(const char *file, int line);		/* LWIP_ASSERT_CORE_LOCKED when NETFIX_CORE_CHECK */
extern volatile uint8_t netcore_armed;				/* set once lwIP init is done */
extern volatile uint32_t netcore_violations;		/* raw API calls seen without the core lock */

#ifdef __cplusplus
}
#endif

#endif /* NETFIX_H_ */
